# Generated by Django 5.0.3 on 2024-04-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='desctination',
            new_name='destination',
        ),
    ]
